from typing import Final
import os
import re
import time
from get_data import parse_ddmmyy, status_monitoring, timetree_monitoring
from wbgt import get_info
from telegram import Update
from telegram.ext import (
    Application,
    CommandHandler,
    ConversationHandler,
    MessageHandler,
    TypeHandler,
    filters,
    ContextTypes,
)
from openai import AsyncOpenAI
from dotenv import load_dotenv
from datetime import date, datetime

load_dotenv()

TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
BOT_USERNAME: Final = "@firefree_1stcoy_bot"
ASYNC_CLIENT = AsyncOpenAI()
MODEL = "gpt-5.6-luna"
ASK_DATE = 1
ASK_PARADE_STATE = 2
PARADE_CHECK_DISCLAIMER = (
    "Disclaimer: This check was generated by AI and may be incorrect. "
    "Please verify against HR/Timetree."
)
MC_RE = re.compile(r"\bMC\b", re.IGNORECASE)
OFF_LEAVE_RE = re.compile(
    r"\b(?:OFF|OIL|LEAVE|OSL|MC)\b",
    re.IGNORECASE,
)
TELEGRAM_MAX_LEN = 4000
# First update within this window after process start gets a cold-start notice
COLD_START_SECONDS = 45
PROCESS_STARTED_AT = time.monotonic()
WEBHOOK_PATH = os.environ.get("WEBHOOK_PATH", "telegram")

# LLM LOGIC


def get_summary_date(context: ContextTypes.DEFAULT_TYPE) -> date:
    return context.user_data.get("summary_date", date.today())


def filter_mc_records(rso_records: list, rsi_records: list) -> list:
    """Keep HR people whose active statuses include MC."""
    filtered = []
    for record in rso_records + rsi_records:
        statuses = record.get("active_statuses") or []
        mc_statuses = [s for s in statuses if MC_RE.search(str(s))]
        if mc_statuses:
            filtered.append(
                {
                    "RANK": record.get("RANK"),
                    "NAME": record.get("NAME"),
                    "active_statuses": mc_statuses,
                }
            )
    return filtered


def filter_off_leave_events(all_events) -> list:
    """Keep Timetree events that look like Off / OIL / Leave / MC."""
    filtered = []
    for _path, events in all_events:
        for event in events:
            summary = str(event.get("summary") or "")
            if OFF_LEAVE_RE.search(summary):
                filtered.append(event)
    return filtered


async def split_and_reply(update: Update, text: str):
    """Send text in chunks under Telegram's message length limit."""
    if len(text) <= TELEGRAM_MAX_LEN:
        await update.message.reply_text(text)
        return
    start = 0
    while start < len(text):
        await update.message.reply_text(text[start : start + TELEGRAM_MAX_LEN])
        start += TELEGRAM_MAX_LEN


async def generate_llm_response(rso_active, rsi_active, timetree_text, on: date):
    rso_active_text = rso_active
    rsi_active_text = rsi_active
    prompt = f"""You are an assistant that generates the daily company summary for 1st Company, 48 Singapore Armoured Regiment (48SAR).

Your goal is to produce a concise, easy-to-read Telegram update for today's activities.

## Input
Date today: {on}

Medical Status data:
{rso_active_text}
{rsi_active_text}

Calendar data (Activities, Off & Leave):
{timetree_text}

## Source of Truth

Generate each section independently using only its specified source.

- **Medical Statuses** → Use ONLY the Medical Status data.
- **Activities Today** → Use ONLY the Calendar data.
- **Personnel on Off/Leave** → Use ONLY the Calendar data.

Never move information between sections or infer information that is not explicitly present.

## Interpretation Rules

### Medical Statuses

Treat the following as medical statuses:
- MC (Medical Certificate)
- LD (Excuse Light Duty)
- RMJ (Excuse Running, Marching, Jumping)
- MA (Medical Appointment)
- Any status beginning with "Excuse"
- Any status beginning with "Ex" (e.g. Ex Firearms, Ex Heavy Machinery, Ex Uniform, Ex Dusty Environment)

Notes:
- "Ex" is short for "Excuse".
- Combine RSI and RSO into a single Medical Statuses section.
- If the same person has multiple active statuses, consolidate them into one entry.
- Preserve the original description and duration.
- Do not invent or rewrite medical information.

### Activities

- Any calendar event that is not an Off or Leave is an activity.
- Leave unknown acronyms exactly as written.
- Do not attempt to expand unknown acronyms.

### Off / Leave

- OIL means Off In Lieu and should be treated as an Off.
- Only include personnel if the Calendar data explicitly states they are on Off, OIL or Leave.
- Do NOT infer that someone is on Off because they are on MC, LD, RMJ, MA or any Excuse status.
- Not necessary to provide a timeframe for the Off or Leave. Just say that a person is Off/Leave and that should be sufficient.

## Output Format

Begin with:

📅 1 Coy Daily Summary (<today's date>)

Then output the following sections in this order.

🏃 Activities 🏃
- List each activity on its own line beginning with "•".
- Do not include Off or Leave here.
- If there are no activities, write:
  • None

🏥 Medical Statuses 🏥

For each person:

• <RANK> <NAME>
  - One line per active status in the format:
    `<Status Type> — <Description> (<Timeframe>)`

Examples:

• PTE HE MINGZHE
  MC — Sore Throat (3–4 Aug)

• PTE LUKE JOSHUA LOW
  Ex Firearms (5 Jun–27 Aug)
  Ex Heavy Machinery (5 Jun–27 Aug)

Formatting rules:
- Do not use labels like "Type", "Description", or "Timeframe".
- Keep each status on a single line whenever possible.
- If a description already contains the status (e.g. "84D Ex Firearms"), do not repeat it. Output simply:
  Ex Firearms (5 Jun–27 Aug)
- Format dates in a human-readable style (e.g. 3 Aug, 27 Aug, 5 Jun–27 Aug) instead of YYMMDD.
- Preserve all information while keeping it concise.

🏠 Off / Leave 🏠

For each person:

• <RANK> <NAME>

Formatting rules:
- If there are no personnel on Off/Leave, write:
  • None
- No need to say "Off until (date). Just an indication that a person is off today is sufficient.

## General Requirements

- Always display personnel as RANK NAME.
- Preserve names exactly as provided.
- Do not invent, infer or reclassify information.
- Keep the message concise and easy to scan on a mobile phone.
- Use Telegram Markdown formatting only.
- Avoid unnecessary blank lines while maintaining readability."""

    resp = await ASYNC_CLIENT.responses.create(model=MODEL, input=prompt)
    return resp.output_text


async def generate_parade_check_response(
    parade_state: str, mc_records: list, off_leave_events: list, on: date
):
    prompt = f"""You are checking a company parade state against ground-truth data.

## Selected summary date
{on.isoformat()} ({on.strftime("%d%m%y")})

## Ground truth — Medical Certificates from HR (Google Sheet)
{mc_records}

## Ground truth — Off / OIL / Leave (and MC if present) from Timetree
{off_leave_events}

## User-submitted parade state
{parade_state}

## Rules
- Generate a Telegram friendly response in list format for easy readability by a human.
- Use ONLY the HR MC list and Timetree Off/OIL/Leave(/MC) list as ground truth for absences.
- Ignore excuses, LD, RMJ.
- Check for possible issues:
  1. Date in the parade state header vs the selected summary date
  2. Headcount / present-vs-strength tallies that look wrong
  3. Spelling/typos in structure or labels (IGNORE spelling of personal names)
  4. Items claimed in the parade state (MC / Off / Leave) that are NOT in Timetree/HR
  5. People/statuses present in Timetree/HR that are MISSING from the parade state
- Output ONLY a concise, human-readable bullet list of possible issues. State if something is present in TimeTree/Google Drive but not the parade state or vice versa.
- If there are no issues, reply with: No issues found.
- Do NOT rewrite or output a full corrected parade state.
- Do NOT invent people or statuses not present in the inputs.
- DO NOT USE ** for formatting.
"""
    resp = await ASYNC_CLIENT.responses.create(model=MODEL, input=prompt)
    return resp.output_text


def format_wbgt_cat_haze(info: dict) -> str:
    """Turn get_info() output into a short human-readable Telegram message."""
    lines = ["🌡 WBGT / CAT / Haze"]

    wbgt = info.get("wbgt")
    lines.append("")
    lines.append("WBGT")
    if not wbgt:
        lines.append("• No data available")
    else:
        lines.append(f"• Camp: {wbgt.get('camp') or '—'}")
        wbgt_val = wbgt.get("wbgt")
        lines.append(
            f"• Reading: {wbgt_val}℃" if wbgt_val is not None else "• Reading: —"
        )
        lines.append(f"• Category: {wbgt.get('category') or '—'}")
        lines.append(f"• Updated: {wbgt.get('updated_at') or '—'} hrs")

    cat = info.get("cat") or {}
    lines.append("")
    lines.append("CAT")
    lines.append(f"• Sector: {cat.get('sector') or '—'}")
    lines.append(f"• Status: {cat.get('status') or '—'}")
    if cat.get("start") and cat.get("end"):
        lines.append(f"• Window: {cat['start']}–{cat['end']} hrs")
    else:
        lines.append("• Window: —")

    psi = info.get("psi")
    lines.append("")
    lines.append("Haze (PSI)")
    if not psi or len(psi) < 3:
        lines.append("• No data available")
    else:
        region, timestamp, value = psi
        # e.g. 2026-08-03T17:00:00+08:00 → 03 Aug 2026 17:00
        display_time = timestamp
        try:
            display_time = datetime.fromisoformat(timestamp).strftime("%d %b %Y %H:%M")
        except (TypeError, ValueError):
            pass
        lines.append(f"• Region: {region}")
        lines.append(f"• 24h PSI: {value}")
        lines.append(f"• Updated: {display_time}")
    lines.append(
        "\nHaze data pulled from NEA API. WBGT and Cat statuses pulled from Telegram channels."
    )

    return "\n".join(lines)


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    on = get_summary_date(context)
    await update.message.reply_text(
        "Hello, thanks for chatting with the Fire Free 1st Coy bot!\n"
        "Commands:\n"
        "/summarise — Summary of things going on on a particular date (pulled from TimeTree calendars and HR sheets) (can use set_date to set a date that is NOT today)\n"
        "/set_date — set the summary date (DDMMYY)\n"
        "/check_date — show the current summary date\n"
        "/check_parade_state — check a pasted parade state against HR/Timetree\n"
        "/wbgt_cat_haze — current WBGT, CAT, and PSI (haze)\n"
        f"Current summary date: {on.strftime('%d %b %Y')}"
    )


async def wbgt_cat_haze_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Fetching WBGT, CAT, and PSI…")
    try:
        info = get_info()
    except Exception as exc:
        await update.message.reply_text(f"Failed to fetch data: {exc}")
        return
    await update.message.reply_text(format_wbgt_cat_haze(info))


async def summarise_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    on = get_summary_date(context)
    await update.message.reply_text(
        f"Generating summary for {on.strftime('%d %b %Y')}… this may take a minute."
    )
    await update.message.reply_text("Pulling info from TimeTree...")
    all_events = timetree_monitoring(on)
    await update.message.reply_text("Pulling info from Google Drive HR sheet...")
    result = status_monitoring(on)
    if isinstance(result, str):
        await update.message.reply_text(result)
        return
    rso_active, rsi_active = result
    rso = rso_active.to_dict(orient="records")
    rsi = rsi_active.to_dict(orient="records")
    await update.message.reply_text("Generating summary using GPT 5.6 luna...")
    op = await generate_llm_response(rso, rsi, all_events, on)
    await update.message.reply_text(op)


async def check_date_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    on = get_summary_date(context)
    await update.message.reply_text(
        f"Current summary date: {on.strftime('%d %b %Y')} ({on.strftime('%d%m%y')})"
    )


async def set_date_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # Allow /set_date DDMMYY in one step
    if context.args:
        try:
            on = parse_ddmmyy(context.args[0].strip())
        except ValueError:
            await update.message.reply_text(
                "Invalid date. Use DDMMYY, e.g. /set_date 040826"
            )
            return ConversationHandler.END
        context.user_data["summary_date"] = on
        await update.message.reply_text(
            f"Summary date set to {on.strftime('%d %b %Y')}"
        )
        return ConversationHandler.END

    await update.message.reply_text(
        "Enter the summary date as DDMMYY (e.g. 040826), or /cancel:"
    )
    return ASK_DATE


async def receive_date(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = (update.message.text or "").strip()
    try:
        on = parse_ddmmyy(text)
    except ValueError:
        await update.message.reply_text(
            "Invalid date. Try again as DDMMYY (e.g. 040826), or /cancel."
        )
        return ASK_DATE
    context.user_data["summary_date"] = on
    await update.message.reply_text(f"Summary date set to {on.strftime('%d %b %Y')}")
    return ConversationHandler.END


async def check_parade_state_command(
    update: Update, context: ContextTypes.DEFAULT_TYPE
):
    await update.message.reply_text("Please provide a parade state")
    return ASK_PARADE_STATE


async def receive_parade_state(update: Update, context: ContextTypes.DEFAULT_TYPE):
    parade_state = (update.message.text or "").strip()
    if not parade_state:
        await update.message.reply_text(
            "Parade state was empty. Please paste a parade state, or /cancel."
        )
        return ASK_PARADE_STATE

    on = get_summary_date(context)
    await update.message.reply_text(
        f"Checking parade state for {on.strftime('%d %b %Y')}… this may take a minute."
    )
    await update.message.reply_text("Pulling info from TimeTree...")
    all_events = timetree_monitoring(on)
    await update.message.reply_text("Pulling info from Google Drive HR sheet...")
    result = status_monitoring(on)
    if isinstance(result, str):
        await update.message.reply_text(result)
        return ConversationHandler.END

    rso_active, rsi_active = result
    rso = rso_active.to_dict(orient="records")
    rsi = rsi_active.to_dict(orient="records")
    mc_records = filter_mc_records(rso, rsi)
    off_leave_events = filter_off_leave_events(all_events)

    await update.message.reply_text("Checking parade state with GPT 5.6 luna...")
    analysis = await generate_parade_check_response(
        parade_state, mc_records, off_leave_events, on
    )
    reply = f"{analysis.strip()}\n\n{PARADE_CHECK_DISCLAIMER}"
    await split_and_reply(update, reply)
    return ConversationHandler.END


async def cancel_conversation(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Cancelled.")
    return ConversationHandler.END


def handle_response(text: str) -> str:
    return "i'm working on it..."


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message_type: str = update.message.chat.type  # group or pm
    text: str = update.message.text

    print(f'User ({update.message.chat.id}) in {message_type}: "{text}"')

    if message_type == "group":
        if BOT_USERNAME in text:
            new_text: str = text.replace(BOT_USERNAME, "").strip()
            response: str = handle_response(new_text)
        else:
            return
    else:
        response: str = handle_response(text)

    print("Bot:", response)
    await update.message.reply_text(response)


async def error(update: Update, context: ContextTypes.DEFAULT_TYPE):
    print(f"Update {update} caused error {context.error}")


async def notify_cold_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """On free-tier cold starts, tell the user the bot is waking up (once per boot)."""
    if context.application.bot_data.get("cold_start_notice_sent"):
        return
    context.application.bot_data["cold_start_notice_sent"] = True

    uptime = time.monotonic() - PROCESS_STARTED_AT
    if uptime > COLD_START_SECONDS:
        return

    message = update.effective_message
    if message is None:
        return

    await message.reply_text("Waking up… one moment.")


async def test_llm(on: date | None = None):
    on = on or date.today()
    all_events = timetree_monitoring(on)
    result = status_monitoring(on)
    if isinstance(result, str):
        return result
    rso_active, rsi_active = result
    rso = rso_active.to_dict(orient="records")
    rsi = rsi_active.to_dict(orient="records")
    op = await generate_llm_response(rso, rsi, all_events, on)
    return op


def _webhook_base_url() -> str | None:
    """Public HTTPS base URL for Telegram webhooks (Render sets RENDER_EXTERNAL_URL)."""
    for key in ("WEBHOOK_URL", "RENDER_EXTERNAL_URL"):
        value = (os.environ.get(key) or "").rstrip("/")
        if value:
            return value
    return None


if __name__ == "__main__":
    print("Starting bot...")
    app = Application.builder().token(TOKEN).build()

    set_date_conv = ConversationHandler(
        entry_points=[CommandHandler("set_date", set_date_command)],
        states={
            ASK_DATE: [MessageHandler(filters.TEXT & ~filters.COMMAND, receive_date)],
        },
        fallbacks=[CommandHandler("cancel", cancel_conversation)],
    )

    check_parade_conv = ConversationHandler(
        entry_points=[CommandHandler("check_parade_state", check_parade_state_command)],
        states={
            ASK_PARADE_STATE: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, receive_parade_state)
            ],
        },
        fallbacks=[CommandHandler("cancel", cancel_conversation)],
    )

    # Cold-start notice runs before other handlers
    app.add_handler(TypeHandler(Update, notify_cold_start), group=-1)

    # commands
    app.add_handler(CommandHandler("start", start_command))
    app.add_handler(CommandHandler("summarise", summarise_command))
    app.add_handler(CommandHandler("check_date", check_date_command))
    app.add_handler(CommandHandler("wbgt_cat_haze", wbgt_cat_haze_command))
    app.add_handler(set_date_conv)
    app.add_handler(check_parade_conv)

    # messages (after ConversationHandlers so date/parade replies are captured first)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    # errors
    app.add_error_handler(error)

    base_url = _webhook_base_url()
    if base_url:
        port = int(os.environ.get("PORT", "8443"))
        webhook_url = f"{base_url}/{WEBHOOK_PATH}"
        print(f"Webhook mode → {webhook_url} (port {port})")
        app.run_webhook(
            listen="0.0.0.0",
            port=port,
            url_path=WEBHOOK_PATH,
            webhook_url=webhook_url,
            drop_pending_updates=True,
        )
    else:
        # Local/dev without a public URL: fall back to polling
        print("No WEBHOOK_URL/RENDER_EXTERNAL_URL set — polling for local use.")
        print("Polling...")
        app.run_polling(poll_interval=3)
